(function () {
  const INCH_TO_PT = 72;
  const letter = { width: 8.5, height: 11, unit: "in" };

  const makeAverySheet = ({
    id,
    displayName,
    category,
    pageSize = letter,
    labelSize,
    rows,
    columns,
    margins,
    gaps,
    safeZone,
    photoBox,
    textRules,
    css,
    material,
  }) => ({
    id,
    displayName,
    category,
    pageSize,
    labelSize,
    margins,
    rows,
    columns,
    gaps,
    safeZone,
    supportsPhoto: Boolean(photoBox),
    photoBox,
    textRules,
    pdfMode: "avery-sheet",
    capacity: rows * columns,
    css,
    material,
  });

  const templates = {
    "avery-94207-classroom": makeAverySheet({
      id: "avery-94207-classroom",
      displayName: "Avery 94207 - Small, 2\" x 4\"",
      category: "Classroom Labels",
      labelSize: { width: 4, height: 2, unit: "in" },
      rows: 5,
      columns: 2,
      margins: { top: 0.5, right: 0.15625, bottom: 0.5, left: 0.15625, unit: "in" },
      gaps: { row: 0, column: 0.1875, unit: "in" },
      safeZone: { top: 0.12, right: 0.12, bottom: 0.12, left: 0.12, unit: "in" },
      photoBox: { x: 0.12, y: 0.28, width: 1.28, height: 1.28, unit: "in", fit: "contain", radius: 0.08 },
      textRules: {
        layout: "horizontal",
        name: { max: 25, min: 11, lineHeight: 1.05, wrap: false },
        title: { max: 13, min: 8, lineHeight: 1 },
        classroom: { max: 12, min: 7, lineHeight: 1.1, optional: true },
      },
      css: { title: "Avery 94207 sheet layout", countLabel: "10 labels per sheet", className: "sheet-94207", scaleClass: "avery-template-small" },
    }),
    "avery-6874-classroom": makeAverySheet({
      id: "avery-6874-classroom",
      displayName: "Avery 6874 - Medium, 3\" x 3.75\"",
      category: "Classroom Labels",
      labelSize: { width: 3.75, height: 3, unit: "in" },
      rows: 3,
      columns: 2,
      margins: { top: 0.9, right: 0.56, bottom: 0.9, left: 0.56, unit: "in" },
      gaps: { row: 0.44, column: 0.43, unit: "in" },
      safeZone: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2, unit: "in" },
      photoBox: { x: 1.25, y: 0.24, width: 1.25, height: 1.25, unit: "in", fit: "contain", radius: 0.08 },
      textRules: {
        layout: "vertical",
        name: { max: 18, min: 12, lineHeight: 1.05, wrap: false },
        title: { max: 11, min: 8, lineHeight: 1 },
        classroom: { max: 10, min: 7, lineHeight: 1.1, optional: true },
      },
      css: { title: "Avery 6874 sheet layout", countLabel: "6 labels per sheet", className: "sheet-6874", scaleClass: "avery-template-medium" },
    }),
    "avery-94256-classroom": makeAverySheet({
      id: "avery-94256-classroom",
      displayName: "Avery 94256 - Large, 5\" x 3.5\"",
      category: "Classroom Labels",
      pageSize: { width: 11, height: 8.5, unit: "in" },
      labelSize: { width: 5, height: 3.5, unit: "in" },
      rows: 2,
      columns: 2,
      margins: { top: 0.55, right: 0.25, bottom: 0.55, left: 0.25, unit: "in" },
      gaps: { row: 0.4, column: 0.5, unit: "in" },
      safeZone: { top: 0.25, right: 0.25, bottom: 0.25, left: 0.25, unit: "in" },
      photoBox: { x: 1.73, y: 0.3, width: 1.55, height: 1.55, unit: "in", fit: "contain", radius: 0.08 },
      textRules: {
        layout: "vertical",
        name: { max: 28, min: 12, lineHeight: 1.05, wrap: false },
        title: { max: 13, min: 9, lineHeight: 1 },
        classroom: { max: 12.5, min: 8, lineHeight: 1.1, optional: true },
      },
      css: { title: "Avery 94256 sheet layout", countLabel: "4 labels per sheet", className: "sheet-94256", scaleClass: "avery-template-large" },
    }),
    "avery-61503-feeding": makeAverySheet({
      id: "avery-61503-feeding",
      displayName: "Avery 61503 - 2\" x 3-3/4\"",
      category: "Infant Feeding Labels",
      material: "Removable bottle labels",
      labelSize: { width: 3.75, height: 2, unit: "in" },
      rows: 5,
      columns: 2,
      margins: { top: 0.5, right: 0.5, bottom: 0.5, left: 0.5, unit: "in" },
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.1, right: 0.1, bottom: 0.1, left: 0.1, unit: "in" },
      photoBox: { x: 2.62, y: 0.12, width: 0.96, height: 1.1, unit: "in", fit: "cover", radius: 0.08 },
      textRules: {
        name: { max: 38, min: 9, lineHeight: 1, wrap: false },
        title: { max: 11, min: 6, lineHeight: 1 },
        dob: { max: 9.8, min: 6, lineHeight: 1.1 },
        fields: { max: 9.4, min: 6, lineHeight: 1.1 },
      },
      css: { pageClass: "feeding-sheet-page feeding-sheet-61503", countLabel: "10 labels per sheet" },
    }),
    "avery-94069-feeding": makeAverySheet({
      id: "avery-94069-feeding",
      displayName: "Avery 94069 - 2\" x 2\"",
      category: "Infant Feeding Labels",
      material: "Square waterproof label format",
      labelSize: { width: 2, height: 2, unit: "in" },
      rows: 5,
      columns: 4,
      margins: { top: 0.5, right: 0.25, bottom: 0.5, left: 0.25, unit: "in" },
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.08, right: 0.08, bottom: 0.08, left: 0.08, unit: "in" },
      photoBox: { x: 1.34, y: 0.2, width: 0.52, height: 0.52, unit: "in", fit: "cover", radius: 0.08 },
      textRules: {
        name: { max: 24, min: 8, lineHeight: 1, wrap: false },
        photoName: { max: 15.5, min: 7, lineHeight: 1, wrap: false },
        title: { max: 11, min: 6, lineHeight: 1 },
        dob: { max: 7, min: 5.5, lineHeight: 1.1 },
        fields: { max: 7.5, min: 5.5, lineHeight: 1.1 },
      },
      css: { pageClass: "feeding-sheet-page feeding-sheet-94069", countLabel: "20 labels per sheet" },
    }),
    "avery-94200-water-milk": makeAverySheet({
      id: "avery-94200-water-milk",
      displayName: "Avery 94200 - Bulk Upload Labels",
      category: "Bulk Upload Labels",
      labelSize: { width: 2.625, height: 1, unit: "in" },
      rows: 10,
      columns: 3,
      margins: { top: 0.5, right: 0.19, bottom: 0.5, left: 0.19, unit: "in" },
      gaps: { row: 0, column: 0.13, unit: "in" },
      safeZone: { top: 0.08, right: 0.1, bottom: 0.08, left: 0.1, unit: "in" },
      photoBox: null,
      textRules: {
        name: { max: 21, min: 20, lineHeight: 1.18, wrap: false },
        title: { max: 11, min: 8, lineHeight: 1 },
      },
      css: { pageClass: "bulk-pdf-page bulk-pdf-94200-page", countLabel: "30 labels per sheet" },
    }),
    "avery-94208-clothing": makeAverySheet({
      id: "avery-94208-clothing",
      displayName: "Avery 94208 - Clothing Labels",
      category: "Bulk Upload Labels",
      labelSize: { width: 1.75, height: 0.667, unit: "in" },
      rows: 20,
      columns: 3,
      margins: { top: 0.34, right: 1.38, bottom: 0.34, left: 1.38, unit: "in" },
      gaps: { row: 0.03, column: 0.25, unit: "in" },
      safeZone: { top: 0.04, right: 0.06, bottom: 0.04, left: 0.06, unit: "in" },
      photoBox: null,
      textRules: { name: { max: 10, min: 6, lineHeight: 1, wrap: false } },
      css: { pageClass: "bulk-pdf-page bulk-pdf-94208-page", countLabel: "60 labels per sheet" },
    }),
    "community-standard-cubby": {
      id: "community-standard-cubby",
      displayName: "Community Playthings Standard Cubby Insert",
      category: "Community Playthings Labels",
      pageSize: { width: 14, height: 8.5, unit: "in" },
      labelSize: { width: 10.85, height: 2.23, unit: "in" },
      margins: { top: 0.19, right: 0.19, bottom: 0.19, left: 0.19, unit: "in" },
      rows: 1,
      columns: 1,
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.16, right: 0.38, bottom: 0.77, left: 0.2, unit: "in" },
      supportsPhoto: true,
      photoBox: { x: 0.2, y: 0.16, width: 1.34, height: 1.34, unit: "in", fit: "contain", radius: 0.08 },
      textRules: { name: { max: 70, min: 22, lineHeight: 1.05, wrap: false, maxLines: 1 } },
      pdfMode: "single",
      cutGuide: "community-arch",
      css: { geometryKey: "standard", pageWidth: 1008, pageHeight: 612, nameSize: 70, nameMin: 22 },
    },
    "community-compact-cubby": {
      id: "community-compact-cubby",
      displayName: "Community Playthings Compact Cubby Insert",
      category: "Community Playthings Labels",
      pageSize: { width: 8.5, height: 11, unit: "in" },
      labelSize: { width: 6.85, height: 1.72, unit: "in" },
      margins: { top: 0.17, right: 0.17, bottom: 0.17, left: 0.17, unit: "in" },
      rows: 1,
      columns: 1,
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.14, right: 0.3, bottom: 0.64, left: 0.18, unit: "in" },
      supportsPhoto: true,
      photoBox: { x: 0.18, y: 0.14, width: 0.96, height: 0.96, unit: "in", fit: "contain", radius: 0.08 },
      textRules: { name: { max: 52, min: 16, lineHeight: 1.05, wrap: false, maxLines: 1 } },
      pdfMode: "single",
      cutGuide: "community-arch",
      css: { geometryKey: "compact", pageWidth: 612, pageHeight: 792, nameSize: 52, nameMin: 16 },
    },
    "community-infant-cubby": {
      id: "community-infant-cubby",
      displayName: "Community Playthings Infant Cubby Insert",
      category: "Community Playthings Labels",
      pageSize: { width: 11, height: 8.5, unit: "in" },
      labelSize: { width: 4.24, height: 6.25, unit: "in" },
      margins: { top: 0.19, right: 0.19, bottom: 0.19, left: 0.19, unit: "in" },
      rows: 1,
      columns: 1,
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.48, right: 0.4, bottom: 0.7, left: 0.4, unit: "in" },
      supportsPhoto: true,
      photoBox: { x: 0.9, y: 1.94, width: 2.45, height: 2.45, unit: "in", fit: "contain", radius: 0.08 },
      textRules: { name: { max: 34, min: 18, lineHeight: 1.04, wrap: true, maxLines: 2 } },
      pdfMode: "single",
      cutGuide: "community-oval",
      css: { geometryKey: "infant", pageWidth: 792, pageHeight: 612, nameSize: 42, nameMin: 22 },
    },
    "community-basket-label": {
      id: "community-basket-label",
      displayName: "Community Playthings Basket Label",
      category: "Community Playthings Labels",
      pageSize: { width: 5, height: 1.5, unit: "in" },
      labelSize: { width: 5, height: 1.5, unit: "in" },
      margins: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06, unit: "in" },
      rows: 1,
      columns: 1,
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.08, right: 0.08, bottom: 0.08, left: 0.08, unit: "in" },
      supportsPhoto: true,
      photoBox: { x: 0.22, y: 0.25, width: 1.0, height: 1.0, unit: "in", fit: "cover", radius: 0.08 },
      textRules: { name: { max: 34, min: 16, lineHeight: 1, wrap: false } },
      pdfMode: "single",
      cutGuide: "rectangle",
      css: { pageWidth: 360, pageHeight: 108, nameSize: 20, nameMin: 12 },
    },
    "welcome-sign": {
      id: "welcome-sign",
      displayName: "Welcome Sign PDF",
      category: "Document Outputs",
      pageSize: letter,
      labelSize: letter,
      margins: { top: 0.8, right: 0.8, bottom: 0.85, left: 0.8, unit: "in" },
      rows: 1,
      columns: 1,
      gaps: { row: 0, column: 0, unit: "in" },
      safeZone: { top: 0.8, right: 0.8, bottom: 0.85, left: 0.8, unit: "in" },
      supportsPhoto: true,
      photoBox: { x: 2.75, y: 3.05, width: 3, height: 3, unit: "in", fit: "cover", radius: 0.18 },
      textRules: {
        heading: { max: 68, min: 48, lineHeight: 0.95 },
        name: { max: 78, min: 34, lineHeight: 1.05, wrap: true, maxLines: 2 },
        classroom: { max: 28, min: 16, lineHeight: 1.15, optional: true },
      },
      pdfMode: "document",
    },
  };

  const aliases = {
    94207: "avery-94207-classroom",
    6874: "avery-6874-classroom",
    94256: "avery-94256-classroom",
    61503: "avery-61503-feeding",
    94069: "avery-94069-feeding",
    standard: "community-standard-cubby",
    compact: "community-compact-cubby",
    infant: "community-infant-cubby",
    basket: "community-basket-label",
    "Student Name": "avery-94200-water-milk",
    "Student Name + Water": "avery-94200-water-milk",
    "Student Name + Milk": "avery-94200-water-milk",
    "Formula Labels": "avery-94069-feeding",
    "Breast Milk Labels": "avery-94069-feeding",
    "Clothing Labels": "avery-94208-clothing",
    "Cubby Labels": "avery-94207-classroom",
    "Cot Labels": "avery-94207-classroom",
    "Crib Labels": "avery-94207-classroom",
    "Welcome Sign PDF": "welcome-sign",
  };

  templates["formula-labels"] = {
    ...templates["avery-94069-feeding"],
    id: "formula-labels",
    displayName: "Formula Labels",
    category: "Infant Feeding Labels",
    contentVariant: "formula",
    fieldModel: {
      title: "Formula",
      fields: ["Ounces", "Date/Week of"],
      weekdays: ["M", "T", "W", "TH", "F"],
    },
  };

  templates["breast-milk-labels"] = {
    ...templates["avery-94069-feeding"],
    id: "breast-milk-labels",
    displayName: "Breast Milk Labels",
    category: "Infant Feeding Labels",
    contentVariant: "breastmilk",
    fieldModel: {
      title: "Breast Milk",
      fields: ["Ounces", "Date"],
      checks: ["Fresh", "Thawed"],
      followUpFields: ["Date Pumped", "Date Thawed"],
    },
  };

  aliases.formula = "formula-labels";
  aliases.breastmilk = "breast-milk-labels";

  const toPoints = (value) => value * INCH_TO_PT;

  const get = (idOrAlias) => templates[idOrAlias] || templates[aliases[idOrAlias]];

  const getSheetMetrics = (template) => {
    const pageWidth = toPoints(template.pageSize.width);
    const pageHeight = toPoints(template.pageSize.height);
    const marginX = toPoints(template.margins.left);
    const marginY = toPoints(template.margins.top);
    const gapX = toPoints(template.gaps.column);
    const gapY = toPoints(template.gaps.row);
    const labelWidth = toPoints(template.labelSize.width);
    const labelHeight = toPoints(template.labelSize.height);

    return {
      pageWidth,
      pageHeight,
      marginX,
      marginY,
      gapX,
      gapY,
      labelWidth,
      labelHeight,
      cols: template.columns,
      rows: template.rows,
      capacity: template.capacity || template.rows * template.columns,
    };
  };

  window.CareCheckLabelRegistry = {
    INCH_TO_PT,
    templates,
    aliases,
    get,
    getSheetMetrics,
    toPoints,
  };
})();
